name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore MeterOrm.sln

      - name: Build solution
        run: dotnet build MeterOrm.sln --configuration Release --no-restore

      - name: Test solution
        run: dotnet test MeterOrm.sln --configuration Release --no-restore --no-build